import Link from 'next/link';
import {storePolicies,SUPPORT_URL} from '@/lib/store-trust';
import styles from '@/components/store-trust.module.css';
export const metadata={title:'Ayuda, envíos y atención'};
export default function Help(){return <main id="contenido" className="section"><span className="eyebrow">INFORMACIÓN PARA TU COMPRA</span><h1>Antes y después de tu pedido.</h1><p className={styles.intro}>Consulta los detalles antes de confirmar. Para una compra ya realizada, incluye su número de pedido al contactar a la tienda.</p><div className={styles.policies}>
<section id="contacto"><h2>Atención al cliente</h2><p>{storePolicies.hours||'Consulta la disponibilidad de atención antes de esperar una respuesta inmediata.'}</p>{SUPPORT_URL?<a href={SUPPORT_URL} target="_blank" rel="noopener noreferrer">Contactar a Merlyn por WhatsApp ↗</a>:<p>Puedes preparar tu carrito y usar «Concluir pedido por WhatsApp» para conversar con el asesor sobre tu pedido. Entrar al grupo no es obligatorio.</p>}</section>
<section id="contenido-paquetes"><h2>Contenido y surtido</h2><p>Cada paquete incluye un desglose de productos y cantidades. Consulta la disponibilidad de tallas, colores o diseños antes de pagar.</p><Link href="/paquetes">Ver paquetes →</Link></section>
<section id="envios"><h2>Preparación y envío</h2><p>{storePolicies.preparation||'El plazo de preparación aún no está publicado. Confírmalo con un asesor antes de pagar.'}</p><p>El costo del envío depende del destino y del paquete. En el pago en línea, consulta y selecciona una cotización en el paso de dirección y envío. Si concluyes por WhatsApp, confirma el costo y el total con el asesor. La estimación de la paquetería no incluye la preparación del pedido.</p></section>
<section id="cambios"><h2>Cambios, devoluciones e incidencias</h2><p>{storePolicies.returns||'Las condiciones específicas de cambios y devoluciones aún no están publicadas. Solicítalas antes de comprar. Si recibiste un pedido con algún problema, contacta a la tienda con su número y una descripción de lo ocurrido para revisar tu caso.'}</p></section>
<section id="pagos"><h2>Revisa el total antes de pagar</h2><p>Los precios se muestran en MXN. El carrito desglosa los productos y paquetes. Cuando el pago con tarjeta está habilitado, se completa en Stripe; también puedes concluir por WhatsApp. No compartas números de tarjeta, códigos de seguridad ni contraseñas en mensajes o en el grupo.</p></section>
</div></main>;}
