import Link from 'next/link';
import {legalBusiness,legalLinks,LEGAL_VERSION} from '@/lib/legal';
import {storePolicies,SUPPORT_URL} from '@/lib/store-trust';
import {CookiePreferences} from './cookie-preferences';
import styles from './legal-page.module.css';

export type LegalKind='privacy'|'terms'|'shipping'|'cookies';
const titles={privacy:'Aviso de privacidad',terms:'Términos de compra',shipping:'Envíos, cambios y devoluciones',cookies:'Política de cookies'};
function Contact(){return <p>Escríbenos al <a href={SUPPORT_URL} target="_blank" rel="noopener noreferrer">WhatsApp de atención: +52 272 128 5563</a>. Incluye tu número de pedido cuando corresponda. No envíes datos de tarjeta ni documentos de identidad en grupos públicos.</p>;}
export function LegalPage({kind}:{kind:LegalKind}){
 const incomplete=!legalBusiness.name||!legalBusiness.address||!legalBusiness.privacyEmail;
 return <main id="contenido" className={styles.page}>
  <Link href="/">← Volver a la tienda</Link><h1>{titles[kind]}</h1><p>Merlyn Mayoreo · Versión {LEGAL_VERSION}</p>
  {(incomplete||!storePolicies.returns||!storePolicies.preparation)&&<aside className={styles.notice}><strong>Información pendiente de completar</strong><p>Falta publicar el domicilio del responsable y precisar los plazos de preparación y atención de devoluciones. El aviso de privacidad no es todavía una versión integral definitiva. Solicita la información faltante a la tienda antes de comprar.</p></aside>}
  <nav aria-label="Información legal">{legalLinks.map(l=><Link key={l.href} href={l.href}>{l.label}</Link>)}</nav>
  {kind==='privacy'&&<>
   <section><h2>1. Responsable y contacto</h2><p>Nombre legal: {legalBusiness.name}. Domicilio del responsable: {legalBusiness.address||'pendiente de publicación'}.</p><p>Correo para solicitudes de privacidad: <a href={'mailto:'+legalBusiness.privacyEmail}>{legalBusiness.privacyEmail}</a>.</p><Contact/></section>
   <section><h2>2. Datos y finalidades necesarias</h2><p>Para registrar, cobrar, preparar y entregar tu pedido tratamos los productos y cantidades elegidos, importe, identificador y estado del pedido y del pago; así como nombre, teléfono, correo y dirección de entrega cuando los proporcionas. También podemos tratar conversaciones de atención, incidencias y datos fiscales que solicites usar para facturación.</p><p>El navegador utiliza almacenamiento para conservar el carrito y recuperar intentos de compra. La infraestructura puede procesar datos técnicos de conexión para operar y proteger el servicio. No solicitamos datos personales sensibles para comprar. Los datos de tarjeta se introducen en Stripe, no en nuestros formularios ni por WhatsApp.</p></section>
   <section><h2>3. Proveedores y servicios externos</h2><p>Stripe procesa el pago cuando eliges tarjeta. Envia.com y la paquetería seleccionada reciben los datos necesarios para cotizar y gestionar la entrega. La infraestructura de alojamiento y almacenamiento da soporte a la tienda y sus imágenes. Estos proveedores pueden operar fuera de México.</p><p>Al continuar por WhatsApp utilizas un servicio de Meta; la tienda genera un enlace con el folio del pedido. Entrar al grupo es opcional y puede hacer visibles tu perfil y teléfono a otros participantes.</p><p><a href="https://stripe.com/privacy" target="_blank" rel="noopener noreferrer">Privacidad de Stripe</a> · <a href="https://www.whatsapp.com/legal/privacy-policy" target="_blank" rel="noopener noreferrer">Privacidad de WhatsApp</a></p></section>
   <section><h2>4. Publicidad opcional con Meta</h2><p>Solo después de aceptar publicidad cargamos el píxel de Meta para medir visitas. Al iniciar un pago con consentimiento y cookies publicitarias disponibles, guardamos identificadores _fbp/_fbc y el tipo de navegador para enviar a Meta la compra confirmada: fecha, identificador del evento, importe MXN, productos, cantidades y precios.</p><p>No incluimos nombre, correo, teléfono, dirección ni datos de tarjeta en ese evento de compra. No hemos habilitado coincidencias avanzadas automáticas. La conexión del navegador con Meta puede comunicar información técnica, como su IP. Rechazar publicidad no impide comprar.</p><p>La preferencia del pedido se captura al iniciar el pago. Cambiarla después no modifica una sesión de pago ya abierta; si necesitas limitar ese tratamiento, contacta a la tienda. Retirar el permiso no elimina eventos ya enviados.</p><CookiePreferences/></section>
   <section><h2>5. Acceso, rectificación, cancelación y oposición</h2><p>Puedes solicitar acceso a tus datos, corregirlos, pedir su cancelación u oponerte al tratamiento, así como revocar tu consentimiento o limitar su uso. Escribe a <a href={'mailto:'+legalBusiness.privacyEmail}>{legalBusiness.privacyEmail}</a> indicando tu nombre, medio de respuesta, derecho que deseas ejercer y los datos o pedido relacionados. Te indicaremos un medio apropiado para acreditar tu identidad; no publiques identificaciones en el grupo.</p><p>La solicitud se atenderá conforme a los requisitos y plazos legales aplicables. Puede ser necesario conservar información por obligaciones legales o para atender una compra o reclamación; te informaremos de las limitaciones que correspondan.</p><Contact/></section>
   <section><h2>6. Conservación, testimonios y cambios</h2><p>Los pedidos y comunicaciones se conservan para atender compras y obligaciones legales. Los identificadores publicitarios del pedido se eliminan tras el envío exitoso de la conversión; los intentos fallidos requieren depuración según la política interna de conservación, aún pendiente de formalizar.</p><p>Las fotografías y testimonios deben contar con autorización para su publicación. Puedes solicitar su retiro y señalar la imagen o página correspondiente. Esta versión se actualizará en esta misma dirección; cambios en finalidades opcionales requerirán revisar el consentimiento correspondiente.</p></section>
  </>}
  {kind==='terms'&&<>
   <section><h2>Productos y precios</h2><p>Vendemos productos individuales y paquetes de mayoreo. Revisa el desglose, cantidades y descripción de cada artículo. Los precios se muestran en MXN e incluyen los impuestos indicados por la tienda. El envío se desglosa por separado antes del pago.</p><p>El precio por volumen de productos individuales se calcula con las cantidades acumuladas del mismo grupo, según las reglas vigentes. Los bundles tienen su propio precio. Modificar cantidades puede cambiar el precio unitario y el total. No se garantiza una combinación de diseños, colores o tallas distinta de lo expresamente ofrecido.</p></section>
   <section><h2>Cómo se registra y paga un pedido</h2><p>Puedes comprar sin crear una cuenta. Al concluir por WhatsApp se registra un pedido pendiente y se abre un mensaje con su folio; debes enviarlo para continuar con atención. Crear ese folio no acredita un pago.</p><p>Cuando esté disponible, el pago con tarjeta se realiza en Stripe después de capturar la dirección y elegir una tarifa de envío. El pago se confirma en el servidor; volver a la tienda no basta para considerarlo pagado. Si hay un error o un cobro sin confirmación, contáctanos con el folio antes de crear otro pedido.</p></section>
   <section><h2>Disponibilidad y entrega</h2><p>Antes de pagar se verifican precios y existencias. Agregar al carrito no garantiza una reserva permanente. Si surge una incidencia con un pedido pagado, contactaremos al cliente para resolverla sin sustituir unilateralmente lo comprado.</p><p>Revisa tu dirección y medio de contacto. Consulta las <Link href="/envios-y-devoluciones">condiciones de envío y devoluciones</Link> antes de concluir. No se limitan los derechos que te correspondan conforme a la legislación aplicable.</p></section>
   <section><h2>Atención y privacidad</h2><Contact/><p>Consulta el <Link href="/privacidad">aviso de privacidad</Link>. La publicidad es opcional y su consentimiento se gestiona por separado de la compra. No es obligatorio entrar al grupo de WhatsApp.</p></section>
  </>}
  {kind==='shipping'&&<>
   <section><h2>Cotización y preparación</h2><p>El costo se calcula con el destino, peso y medidas del pedido. Al pagar en línea seleccionas una tarifa vigente y su importe se incluye en el total. Por WhatsApp, confirma el envío y total con atención antes de pagar. Elegir una tarifa no genera por sí solo una guía.</p><p>{storePolicies.preparation||'Plazo de preparación y horario de corte: pendientes de confirmar por la tienda. Solicítalos antes de pagar.'}</p><p>Los tiempos mostrados por la paquetería son estimaciones de tránsito, no incluyen la preparación y pueden variar por cobertura o incidencias. Si cambia tu dirección, avísanos antes de la salida; puede requerirse una nueva cotización.</p></section>
   <section><h2>Cancelaciones, cambios y devoluciones</h2><p>{storePolicies.returns||'La tienda aún debe confirmar y publicar los plazos, requisitos, costos de retorno y procedimiento de reembolso. Solicita estas condiciones antes de comprar. No se establece aquí una prohibición general de cancelaciones o devoluciones.'}</p><p>Para solicitar atención, indica el folio, lo ocurrido y la solución que solicitas. Si hay daños, faltantes o un artículo incorrecto, conserva el empaque y comparte fotografías cuando sea posible para facilitar la revisión. No envíes mercancía sin coordinar previamente la dirección de retorno.</p><p>Los tiempos y medio de un reembolso se comunicarán al resolver el caso. Estas indicaciones no eliminan garantías ni derechos legales aplicables.</p><Contact/></section>
  </>}
  {kind==='cookies'&&<>
   <section><h2>Protección del servicio</h2><p>La cookie necesaria merlyn-visitor contiene un identificador aleatorio durante 24 horas para distribuir los límites de solicitudes y proteger la tienda de saturación. No se utiliza para publicidad ni se envía a Meta.</p></section>
   <section><h2>Almacenamiento necesario para comprar</h2><p>Usamos almacenamiento local del navegador para el carrito y tu elección de publicidad, y almacenamiento de sesión para recuperar intentos de pedido. No se usan para autorizar cargos. Puedes eliminarlos desde tu navegador, pero podrías perder el carrito y las preferencias guardadas.</p></section>
   <section><h2>Cookies publicitarias opcionales</h2><p>Si aceptas publicidad, el píxel de Meta puede utilizar _fbp y _fbc para relacionar visitas y compras con anuncios. Su disponibilidad y duración dependen de Meta y del navegador. No se carga el píxel si rechazas. Sin estos identificadores no enviamos la conversión de compra desde el servidor.</p><p>El consentimiento se conserva en este navegador hasta que lo cambies o borres su almacenamiento. Las conexiones a servicios externos pueden transmitir datos técnicos de conexión. Consulta la <a href="https://www.facebook.com/privacy/policy/" target="_blank" rel="noopener noreferrer">política de privacidad de Meta</a>.</p><CookiePreferences/></section>
   <section><h2>Cambiar tu decisión</h2><p>Usa «Preferencias de cookies» para aceptar o rechazar publicidad. Puedes seguir comprando si rechazas. Esto detiene nuevos eventos del píxel; no borra los ya enviados ni actualiza automáticamente pedidos cuyo pago ya iniciaste. Para una solicitud sobre un pedido, contacta a atención.</p><p>Stripe y WhatsApp gestionan sus propias cookies en sus servicios. No es necesario aceptar publicidad en la tienda para usarlos.</p></section>
  </>}
 </main>;
}
